# ======================================
# VERSION DECLARATIONS
# ======================================

[versions]
# Core Android and Kotlin
kotlin = "2.1.21"
ksp-version = "2.1.21-2.0.1"
agp = "8.11.1"

# Android SDK Versions
compileSdk = "35"
minSdk = "23"

# AndroidX Libraries
activity-compose = "1.10.1"

# Compose
compose-multiplatform = "1.8.1"

# Dependency Injection
koin = "4.0.2"

local-project-version = "0.1.0"

# Coroutines
kotlinx-coroutines-core = "1.10.2"
kotlinx-coroutines-android = "1.10.2"
kotlinx-coroutines-jvm = "1.10.2"
kotlinx-coroutines-slf4j-version = "1.10.2"
kotlinx-coroutines-swing-version = "1.10.2"

# ======================================
# GRADLE PLUGINS
# ======================================

[plugins]
# Android and Kotlin plugins
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }

# Multiplatform and Compose
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }


# ======================================
# LIBRARY DEPENDENCIES
# ======================================

[libraries]
# Project
platform-coroutines = { module = "com.github.cagdasc.kmp-platform-foundation:coroutines", version.ref = "local-project-version" }
platform-core = { module = "com.github.cagdasc.kmp-platform-foundation:core", version.ref = "local-project-version" }

# ---- Compose ----
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# ---- Coroutines ----
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines-swing-version" }
